RailsGlass/config/routes.rb
GlassRails::Application.routes.draw do
  get "example/index"

  get "example/add_card"

  get "example/get_location"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'example#index'

end

RailsGlass/app/models/user.rb
require "google/api_client"
require "rest_client"
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)

    data = access_token.info

     #   puts data.inspect
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
        user.access_token = access_token.credentials.token
        user.refresh_token = access_token.credentials.refresh_token
        user.token_expires_at = Time.at(access_token.credentials.expires_at)
    end
    user
  end

  def self.get_client(user)
    client = Google::APIClient.new
    client.authorization.scope = 'https://www.googleapis.com/auth/calendar'
    client.authorization.access_token = User.get_current_token(user)
    client
  end

  def self.get_current_token(user)
    if (user.access_token.nil? || (user.token_expires_at.nil? || user.token_expires_at < Time.now))
      data = {
        :client_id => ENV["GOOGLE_KEY"],
        :client_secret => ENV["GOOGLE_SECRET"],
        :refresh_token => user.refresh_token,
        :grant_type => "refresh_token"
      }
      @response = ActiveSupport::JSON.decode(RestClient.post "https://accounts.google.com/o/oauth2/token", data)
      puts @response.to_json
      if @response["access_token"].present?
        user.access_token = @response["access_token"]
        user.token_expires_at = Time.at(Time.now.to_i + @response["expires_in"])
      end
      user.save
    end
    user.access_token
  end

end

RailsGlass/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RailsGlass/app/controllers/example_controller.rb
class ExampleController < ApplicationController
  before_filter :authenticate_user!
  def index
    client = User.get_client(current_user)
    oauth2 = client.discovered_api( "oauth2", "v2" )
    result = client.execute(
      :api_method => oauth2.userinfo.get)
    @name = result.data.name

    render :index
  end

  def add_card
    client = User.get_client(current_user)
    mirror = client.discovered_api('mirror', 'v1')
    timeline_item = mirror.timeline.insert.request_schema.new({ 'text' => "Hello World!" })

    result = client.execute(
      :api_method => mirror.timeline.insert,
      :body_object => timeline_item)

    if result.status == 200
      @message = "Inserted new card with ID #{result.data.id}"
    else
      @message = "An error occurred: #{result.data['error']['message']}"
    end
    render :add_card
  end

  def get_location
    client = User.get_client(current_user)
    mirror = client.discovered_api('mirror', 'v1')
    result = client.execute(
      :api_method => mirror.locations.get,
      :parameters => { 'id' => 'latest' })
    if result.status == 200
      location = result.data
      @message = "Location recorded on: #{location.timestamp}<br />Lat: #{location.latitude}<br />Long: #{location.longitude}<br />Accuracy: #{location.accuracy} meters"
    else
      @message = "An error occurred: #{result.data['error']['message']}"
    end
  end
end

RailsGlass/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def google_oauth2
	    # You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.google_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
end

RailsGlass/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsGlass/app/helpers/example_helper.rb
module ExampleHelper
end

RailsGlass/app/views/example/add_card.html.erb
<h1>Insert Test Timeline Card</h1>
<p><%= @message %></p>

RailsGlass/app/views/example/get_location.html.erb
<h1>Get Last Known Location</h1>
<p><%= raw @message %></p>

RailsGlass/app/views/example/index.html.erb
<h1>Hello <%= @name %></h1>

RailsGlass/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GlassRails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">GlassRails</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
	            <% if user_signed_in? %>
				  <li>
				  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
				  </li>
				<% else %>
				  <li>
				  <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
				  </li>
				<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to 'Insert Test Timeline Card', example_add_card_path %></li>
              <li><%= link_to 'Get Last Known Location', example_get_location_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>